### ISSUE TITLE
Property getFilePath missing in Registry constructor options

### ISSUE THREAD

**Issue by epatpol** [NeekSandhu/monaco-textmate#1]
Following the example it says I still have to define `getFilePath` for the `RegistryOptions`, shouldn't that be removed for this monaco fork?

**Comment by zikaari** [comment]
You're right. I forgot to remove it from the interface, which I'm gonna fix today. But be assured, getFilePath is purged in implementation.

**Comment by epatpol** [comment]
Thanks for the quick update,

Also this might be more of a vscode-textmate question, but 

```typescript
    const registry = new Registry({
        getGrammarDefinition: async (scopeName) => {
            return {
                format: 'json',
                content: await (await fetch(`static/grammars/css.tmGrammar.json`)).text()
            }
        }
    })
```

What happens if I want to support multiple language ids? Do I need to do a switch case with all the scopeNames I support. In that case which default one should I return? AFAIK I cannot return undefined here...

edit: Nevermind this is indeed the method to use for browser user case, I think it should allow undefined though, in the case that it needs to find a grammar definition for a scopeName i.e (typescript) but the developer didn't specify one for this case. WDYT?

**Comment by zikaari** [comment]
If you don't return anything, the Promise stays in pending state. If you return anything else, you get an error.

Best is to create a map of all the scopeNames you think its going to ask for[1], i.e a map of scopeNames to their grammar file URLs. I used `if` block to keep example simple.

[1] Aside from the scopes you know you're gonna need. It's also your responsibility to make sure that you provide dependencies for any other scopeName. For example: `source.php` scope has dependency of `text.html`. Thrown errors will let you know when a dependency is missing. Use the second argument passed to `getGrammarDefintion` to see the dependent scopeName for requested scopeName.

**Comment by zikaari** [comment]
Please see this critical update:
[03c5a4e - use scopeName instead of name prop](https://github.com/NeekSandhu/monaco-textmate/commit/03c5a4e4b4fd0badfb70e6b3d319a7ad4f1b6d0d)

That's the correct way of interacting with any moving part.

**Comment by epatpol** [comment]
Thanks for the update!

However in
>Please see this critical update:
>03c5a4e - use scopeName instead of name prop
>That's the correct way of interacting with any moving part.

That wouldn't compile on my project as `getGrammarDefinition` doesn't accept undefined, which could happen in the example above if the scopeName isn't `source.css` right?

**Comment by zikaari** [comment]
Correct. That's why you must make sure that all the scope names; explicit (the ones you're interested in) and implicit (deps of the formers) are available if need be.

Just start with an explicit one, then errors will let you know what others you need.

Let me know if you get stuck.

**Comment by zikaari** [comment]
BTW keep on playing with one or two grammars but don't bother hand-coding all that for like 40+ languages. I have a nodejs script that will generate that for you. I'll prepare a gist when I get home in 6 hours.

**Comment by epatpol** [comment]
Thanks! I'll explain our situation so this might be more clear for you. In the context of [theia](https://github.com/theia-ide/theia/) which is a web IDE framework I contribute to, we already provide a monaco editor but the problem is that syntax highlighting is currently lacking (monaco provides very basic tokenization as seen [here](https://github.com/theia-ide/theia/issues/1683#issuecomment-385056476)). To extend support for new languages, developers can build and extend extensions to add features to the application. I.e the base framework only supports typescript and c++, but if a java developer wanted support for java, he would need to hook up a java extension to a java language server that implements the LSP (which theia support).

Thanks to your package, I now wanted to try having the syntax highlighting in the frontend part of the application (where monaco resides) using `monaco-textmate`. Following the principles of the framework, what would be ideal is that the core framework supply language highlighting for the core languages like typescript and c++, but someone (an extension developer) could also provide the java grammar so that theia could now also highlight java files correctly. The problem I see (unless I misunderstood `getGrammarDefinition` is that I can't know in advance all the languages that are going to be used.

```typescript
  init() {
        this.registry = new Registry({
            getGrammarDefinition: async scopeName => {
                const grammar = this.grammars.find(grammarDef =>
                    grammarDef.scope === scopeName);
                if (grammar) {
                    return {
                        format: grammar.format,
                        content: grammar.content
                    };
                } else {
                    return {
                        format: 'json',
                        content: ''
                    };
                }
            },
            getFilePath: () => ''
        });

        wireTmGrammars(monaco, this.registry, )
    }
```
As seen above when no grammars are found (because no extension developers supplied an appropriate grammar for the language), I would like it to fail silently and just use the basic monaco language highlighting. To silence the compiler I have to return a dummy `IGrammarDefinition` as getGrammarDefinition` doesn't accept undefined in that case.

Again, thanks for the help, and hopefully I can make a working prototype soon :)

**Comment by zikaari** [comment]
Beautiful. Here's how I'd imagine based on information I have:

Imagine that extension developer is providing advanced language features for Java, which also includes TM based syntax highlighting. Assume the extension dev forgets/fails to provide valid `java.tmLanguage.json` or another `tmLanguage` file that `java.tmLanguage` depends on.

**SPOILER ALERT**: Wrap `wireTmGrammars` in a try-catch and silence everything
___
> Extension code
```javascript
// app.js

import { workspace } from 'theia-runtime'

const javaLanguageSupport = {
    onActivate: () => {
        workspace.registerTextMateGrammarScope('source.java', {
            getGrammarDefinition: () => null // or anything not cool
        })

        workspace.setLanguageTmGrammar('java', 'source.java')
    },
    onDispose: () => { /* impl */ }
}

export default javaLanguageSupport
```
___
> Theia's extension host
```javascript
// extension_api.js (theia-runtime)

import { tmRegistry, langIdToScopeMapping } from './textmate_support'

export default {
    workspace: {
        registerTextMateGrammarScope: (scopeName, provider) => {
            if (provider && 'getGrammarDefinition' in provider) {
                tmRegistry.set(language, provider)
            }
        },
        setLanguaeTmGrammar: (language, scopeName) => {
            langIdToScopeMapping.set(language, scopeName)
        }
    },
    storage: { /* impl */ }
}
```

```javascript
// textmate_support.js

import { editor } from './editor'
import { logger, ERR_CODE } from './telemetry'

export const tmRegistry = new Map()
export const langIdToScopeMapping = new Map()

class TmHypervisor {
    static init() {
        this.registry = new Registry({
            // Call to this will only be triggered by wireTmGrammars, and we can wrap latter in try-catch
            getGrammarDefinition: async (scopeName) => {
                if (tmRegsitry.has(scopeName)) {
                    return tmRegistry.get(scopeName)
                }
            }
        })
    }

    static async activateLanguage(languageId) {
        const scopeName = langIdToScopeMapping.get(languageId)
        const provider = tmRegistry.get(scopeName)
        if (!provider) {
             return false
        }

        try {
            await wireTmGrammars(monaco, this.registry, new Map([[languageId, scopeName]]))
        } catch (err) {
            logger.error(ERR_CODE.TM_LANGUAGE_FATAL, err)
        }
    }
}

TmHypervisor.init()

// Here it's assumed that editor won't open file until this callback's Promise resolves
editor.onBeforeOpenFile(async (path, languageId) => TmHypervisor.activateLanguage(languageId))
```

**Comment by zikaari** [comment]
Also now that I know you guys are working on something very similar to [what I am working on](https://goo.gl/d64cgv), I wrote these packages for the app in question and feel like they might come in handy for theia too.

[text-store &nbsp;| &nbsp;Super performant text container built upon caches](https://www.npmjs.com/package/text-store)
[v-thread &nbsp;&nbsp;&nbsp;| &nbsp;Web workers on steroids made easy](https://www.npmjs.com/package/v-thread)

**Comment by epatpol** [comment]
@NeekSandhu thanks a lot for the help so far. I'll have a look at the packages you mentionned also. I think the only blocker I'm having so far with having a working (hopefully) prototype is the webpack4/3 wasm loading issue. I'll experiment with webpack 3 and see if it works correctly.

**Comment by epatpol** [comment]
Also the suggestion about silencing the error doesn't solve the compilation error, i.e in
```typescript
    static init() {
        this.registry = new Registry({
            // Call to this will only be triggered by wireTmGrammars, and we can wrap latter in try-catch
            getGrammarDefinition: async (scopeName) => {
                if (tmRegsitry.has(scopeName)) {
                    return tmRegistry.get(scopeName)
                }
            }
        })
    }
```

This will definitely fail to compile because tsc complains that `getGrammarDefinition` signature must absolutely return a `Promise<IGrammarDefinition>`, that would work if only the return was `Promise<IGrammarDefinition | undefined>` as with the code above, there is the possibility of the scopeName not being in the registry.

**Comment by zikaari** [comment]
Agree. I'm gonna fix that interface later today

**Comment by zikaari** [comment]
Actually, try returning `null` instead. I tried and TypeScript didn't complain. It also looks more verbose IMO.

**Comment by epatpol** [comment]
I think I'm so close to making it work, but I still have some issues about (I think?) `getGrammarDefinition`. I don't want you to understand everything I did [here](https://github.com/epatpol/theia-1/commit/3ae96484ba4550936c273893499a432cf4eeb040#diff-c70ca2f6d7259845fceaefa6d9075a0eR81) , but it seems I get an error (the one defined [here](https://github.com/NeekSandhu/monaco-textmate/blob/master/src/main.ts#L148) when init is called... I'm trying to debug the library but somehow I think my webpack config is wrong and I don't have sourcemaps for monaco-textmate so it's very difficult to debug. Still WIP :)

**Comment by zikaari** [comment]
That's probably because when format is `json`, the function anticipates a `string` JSON and not a parsed/object JSON.

It is absolutely ridiculous and makes no sense. I'm gonna fix that and have it accept objects as well.

**Comment by epatpol** [comment]
I made a workaround by just using `JSON.stringify()` on the object and it seems to run correctly without errors now. I can see that opening a ts file calls the correct get `getGrammarDefinition` however the highlighting is all broken (having tokens on some random keywords in the comment sections) and not like vscode's one. I'm still investigating, I thought at first maybe my grammar was wrong but it seems alright. For some reasons it adds tokenization to some keywords in the comment sections like so

https://i.imgur.com/TwUzQZn.png

At least everything seems to be correctly hooked now.

**Comment by mofux** [comment]
@epatpol Are you sure you are passing the correct `prevState`? Looks to me like every line is tokenized without the knowledge of the previous line state, which might confuse the parser:
https://github.com/NeekSandhu/monaco-textmate/blob/master/src/main.ts#L183-L199

**Comment by zikaari** [comment]
That part of the puzzel is (or should be) handled here - https://github.com/NeekSandhu/monaco-editor-textmate/blob/master/src/index.ts#L44

**Comment by epatpol** [comment]
Thanks for the tips, yea that's what I was looking at. But because of the webpack issues I'm having with source-loading I currently copied the code from that package in my app so I can quickly debug/modify it.

**Comment by epatpol** [comment]
Yea somehow in my case the endState that's passed down in res.ruleStack isn't the same one when tokenize() is called again. so block scopeName is forgotten and it starts tokenizing comments.

**Comment by zikaari** [comment]
Are you not using monaco-editor-textmate?

**Comment by epatpol** [comment]
I'm actually using it, but because of web pack not loading the source files I just copied the code from it inside my project to test/modify it quickly.

**Comment by zikaari** [comment]
You're right, `src/` is in `.npmignore` so it doesn't get shipped when you npm install `monaco-textmate`. Therefore `source-map-loader` fails to do its job.

I'm gonna fix that too later today.

**Comment by zikaari** [comment]
Bunch of fixes in `2.0.0`. Please run `npm i monaco-textmate` again to update.

> *epatpol:* I'm actually using it, but because of web pack not loading the source files I just copied the code from it inside my project to test/modify it quickly

https://github.com/NeekSandhu/monaco-textmate/commit/68213d2c162adb4e5efb7a3153bb4efb1e58142e - unlist src/ from .npmignore for sourcemap's sake in prod
___
> *epatpol:* I made a workaround by just using JSON.stringify()

https://github.com/NeekSandhu/monaco-textmate/commit/f060ce258fbf972777b0b292ff0999316848c9e2 - IGrammarDefinition now accepts objects when format === 'json'

**Comment by zikaari** [comment]
I have also fixed `.npmignore` of `monaco-editor-textmate` so that should be good too.

PS: Something you might wanna consider - [monaco-editor-textmate#limitation](https://github.com/NeekSandhu/monaco-editor-textmate#limitation)

**Comment by epatpol** [comment]
Amazing for the updates. The limitations are a bit troublesome however. To me it feels like a current monaco problem that you can't override a said language tokenizer because of the built-in tokenizer that will then override the one you just hooked (unless I didn't understand the problem correctly). Is that maybe why they don't use that api `setTokensProvider` in vscode itself? Maybe I can check how they do it instead and do something similar (omitting `monaco-editor-textmate` packages but still using `onigasm` and `monaco-textmate`).

**Comment by epatpol** [comment]
Also even if I delay the custom token provider, I still get the problem where the state isn't correctly passed between tokenizing lines, so comments spanning several lines are not correctly colored. Now at least I should be able to debug `wireTmGrammars` however, so I'll check if it's an easy fix.

**Comment by zikaari** [comment]
Did you try the [workaround](https://github.com/NeekSandhu/monaco-editor-textmate/blob/master/README.md#solution)?

**Comment by epatpol** [comment]
I didn't use it yet as I'm testing with a setTimeout for now (which should make it work correctly), but with this it should still work right? Anyway, debugging `monaco-editor-textmate` would it be possible that the state isn't correctly checked when `equals` is called [here](https://github.com/NeekSandhu/monaco-editor-textmate/blob/master/src/index.ts#L18) ? I tried forking it and using that fork locally to test it but somehow I didn't manage to compile it locally. Anyway next step I'll use the webpack plugin meanwhile.

Thanks again!

update: https://i.imgur.com/Y0yFdMM.png Is that the intended behavior? I feel like it might be part of the reason why it doesn't continue into the comment block scope at the beginning.

**Comment by zikaari** [comment]
I can't really say if `monaco-editor` in your setup is really acknowledging `monaco-textmate` the way it should. I tested out myself and results were pathetic. You see, in your case you're getting "corrupted" tokenization and in my case, I'm not getting tokenization *at all*. Thats the thing that made me doubt `monaco-editor`'s acknowledgement towards `monaco-textmate` and/or `monaco-editor-textmate`.

**BUT...**

I'm fairly confident that `monaco-editor-textmate` appears to be behaving like a good boy.

I temporarily modified `project-folder/node_modules/monaco-editor-textmate/dist/index.js` and added `console.log` before `wireTmGrammars` tokenization hook returns results to `monaco-editor`

```javascript
// project-folder/node_modules/monaco-editor-textmate/dist/index.js (Modified)

// ...

monaco.languages.setTokensProvider(languageId, {
    getInitialState: () => new TokenizerState(monaco_textmate_1.INITIAL),
    tokenize: (line, state) => {
        const res = grammar.tokenizeLine(line, state.ruleStack);
        const ret = {
            endState: new TokenizerState(res.ruleStack),
            tokens: res.tokens.map(token => (Object.assign({}, token, {
                // TODO: At the moment, monaco-editor doesn't seem to accept array of scopes
                scopes: token.scopes[token.scopes.length - 1]
            }))),
        };
        console.log(ret)
        return ret
    }
});

// ...
```

And I got this...

![](https://i.imgur.com/NvlKvI1.png)


## Possible explanation

Perhaps monaco's built-in theming service was never designed to expect TextMate level scope names like `storage.type.function.ts` or `punctuation.definition.parameters.begin.ts` so it fails miserably at that part.

**Comment by zikaari** [comment]
Maybe this is out of context and you might find it ridiculous. But give me a chance...

**I literally dropped `monaco-editor` out of my project a while ago and went with `codemirror` instead**

What??? You say.

Because of all this shit problems I had with `monaco-editor`.

First of all, it comes with too much shit built-in out of the box. Good thing on the surface but nightmare when you wanna modify something. Like right now, for example.

Reasons I dropped monaco:

- Too much built-in shit, like context menus, command pallete etc.
- Shitty `WebWorker` interfaces. AFAIK `monaco` terminates idle `WebWorkers` after a certain timeout (15 seconds I think). That means any worker that was spawned to do language diagonistics or linting or auto-completion or whatever, needs time and resources to build a tree of all the files in project and their imports and stuff before it can do any of aforementioned things. The next thing you know, it's been killed by `monaco-editor` because it knows better than anyone else on what needs to be done.
- Super hard to modify it's appearance (scrollbars is prime example)
- `monaco-editor` messes up `Model` URI's despite being not asked for. `C:\path\to\something` is converted to `c:\path\to\something`. Not a a big problem, but becomes apparant when language services are involved. Also a proof of how `monaco-editor` decides how things should work

**And worst of all...**

- `monaco-editor`'s internals decide how auto-complete items should be sorted before displaying them to the user. **WHAT???** Of course, because apparantely `monaco-editor` is smarter and knows better than Python language service when it comes to what user would expect first on the list.

The last one totally butchers sort order provided by a smart language service which can potentially do auto-completion based on context. Location of cursor/caret, what text comes before, what comes after, maybe some heuristic analysis of stuff, etc.


**But that's the thing, `monaco-editor` was probably not designed to be used at scale where there are million moving parts**

## My switch to CodeMirror

I switched to CodeMirror because of all those nuances.

At this point, I have successfuly implemented a `monaco-textmate` to `codemirror` hooks. Custom theming engine that works with TextMate scope names. An auto-completion system that doesn't overrides sort order and respects language service's decision.

Along with all that, language services that run in web workers **without getting interrupted or killed**. Powered by [`v-thread`](https://www.npmjs.com/package/v-thread). Editor and Workers efficiently sync files using [`text-store`](https://www.npmjs.com/package/text-store) without a problem.

The only things missing are mini-map, and implentation of squigly red lines in the editor for when errors are pointed out by language services.

I have never been happier.

That was my story. Most of CodeMirror implementaion is ready to roll. If you (or you guys) ever consider to make this move please remember that together, as a team, we can reach the stars.

**Comment by zikaari** [comment]
You can see the result of all that [in this video](https://goo.gl/d64cgv). (The editor in the video is `codemirror` wired with `monaco-textmate`)

___

Also regarding my last point about `monaco-editor` butchering auto-completion and how smart language services can provide context driven results. Look at example below:

![](https://i.imgur.com/MjYIH74.png)

We all know that user is 0.00001% likely to care about `widows` and 99% likely to go for `width`. Even if CSS language service was taught a probabilty system, this is what we would get.

**Comment by zikaari** [comment]
> [**_epatpol_**:](https://github.com/NeekSandhu/monaco-textmate/issues/1#issuecomment-390229654) update: https://i.imgur.com/Y0yFdMM.png Is that the intended behavior? I feel like it might be part of the reason why it doesn't continue into the comment block scope at the beginning

See if this helps 🤞

[`82f0f38`](https://github.com/NeekSandhu/monaco-editor-textmate/commit/82f0f384d14d924fd605c179b7e9ffcfea0cbd16) - add `ruleStack` comparison in `TokenizerState.equals` method

Available in `monaco-editor-textmate@1.0.3`

**Comment by zikaari** [comment]
`onigasm`, `monaco-textmate` and `monaco-editor-textmate` are now compiled with target set to `esnext`. 

The reason was to get rid of the extra code generated by TypeScript compiler (`__awaiter`, `__generator`, etc.)

Please re-install all of them again to get the latest and greatest.

**Comment by svenefftinge** [comment]
You can sort completion items by providing the `sortText` property.
https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L4238

**Comment by zikaari** [comment]
😲

How can that be used if we want to have `width` prop before `widows` in a CSS file when user types `wi`?

(As shown in image above)

**Comment by svenefftinge** [comment]
the language service adds `sortText` property for every returned `CompletionItem`, defining the order of them. The default behavior is to use the label for sorting.

**Comment by paul-marechal** [comment]
Does that mean that one should provide the item index returned from the language server autocomplete list ? So that the order of the elements stay the same from how they were fed to monaco ?

**Comment by zikaari** [comment]
Yea ^^^ same question still, because type of `sortText` is string??

**Comment by svenefftinge** [comment]
Yes, if all is sorted already, you could generate `sortText : "0001"`, `sortText : "0002"`, etc.

**Comment by paul-marechal** [comment]
@NeekSandhu about

> Perhaps monaco's built-in theming service was never designed to expect TextMate level scope names like storage.type.function.ts or punctuation.definition.parameters.begin.ts so it fails miserably at that part.

From what I understand, vscode has the same issue when you use the native themes.
For instance, on vscode, themes such as `dark (Visual Studio)` or `light (Visual Studio)` do not support most of textmate tokenization, the colors are just awful. My guess is that we should provide our own theming, just like `dark+` on vscode. Not sure if its the best option, but I don't see how to do else.

**Comment by paul-marechal** [comment]
https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations

**Comment by zikaari** [comment]
Yea I've read that article and as per my understanding the main challenge is that its hard to simulate TextMate selector matching with HTML and CSS **efficiently**.

For example, imagine a token has scope: `source.ts meta.function.ts entity.name.function.ts`

Now, to produce perfect styling, we must honor the parent-child hierarchy of the token. 

Representing that in CSS, not a problem, since it's a just a static one-time thing.

(I'm using SCSS for readability sake)

```scss
.source.ts {
	/* impl */
    .storage.type.ts {
    	/* impl */ 
     }
    .meta.function.ts {
    	/* impl */
    	.entity.name.function.ts {
    		color: #ffffff
    	}
        .storage.type.function.ts {
        	color: #d2d2d2
        }
    }
}
```

But on the HTML side, we need nesting, or more accurately **dynamic, real-time nesting**;

```html
<span class="source.ts">
	<span class="storage.type.ts">const</span>
    <span class="meta.function.ts">
    	<span class="entity.name.function.ts">parseXML</span>
        <span class="punctuation.ts">=</span>
        <span class="storage.type.function.ts">function</span>
    </span>
</span>
```

Imagine adjusting nesting levels of a token *as the user types*. At one point it's 3 levels deep and moment after it's 2 levels deep. And consolidate that with the fact that most text editors run their token tokenization from top to bottom and left  to right, *just once* per change.

___

That I think is the reason why we see `vscode` and `monaco-editor` render their markup like

```html
<span>
	<span class="mtk6">const</span>
	<span class="mtk1">parseXML</span>
	<span class="mtk2">=</span>
	<span class="mtk6">function</span>
</span>
```

**Comment by zikaari** [comment]
For reference `monaco-editor` **has** the potential to consume TextMate themes. Right now; as we speak.

Both `vscode` and `monaco-editor` consume (or can consume) TextMate themes and map the style rules to their internal class names like `mtk2`, `mtk12` etc.

See [`vscode-textmate/src/theme.ts`](https://github.com/Microsoft/vscode-textmate/blob/master/src/theme.ts)

`monaco-editor` uses the exact same method but doesn't expose any interface that allows us to feed it with TextMate themes.

Forking `monaco-editor` and exposing that manually is the only way to success.

**Comment by paul-marechal** [comment]
> monaco-editor uses the exact same method but doesn't expose any interface that allows us to feed it with TextMate themes.

I wonder about that... I am currently doing this:
```ts
        monaco.editor.defineTheme('mehmehmeh', {
            base: 'vs-dark',
            inherit: true,
            colors: theme.colors,
            rules: theme.rules,
        });

        monaco.editor.setTheme('mehmehmeh');
```
I've been able to monkey plug [themes files that I got in the vscode repository](https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json), and so far so good !

The current result is a bit flaky because I am not correctly parsing the theme files (theme dependencies, fighting with webpack to make dynamic requires of the different `.json` files...):

![theia with textmate!](https://user-images.githubusercontent.com/14182238/40844739-b8f7b0a4-6582-11e8-9cd5-afff86bd723a.png)

Looks like it is just a matter of providing the right theme.

**Comment by paul-marechal** [comment]
Also, if you run vscode, you can try the defaults themes that come with the monaco editor: `dark_vs` and `light_vs`, both of them look like they don't support Textmate grammars, because the output was identical to what we had before using TextMate with the correct themes.

**Comment by zikaari** [comment]
Can we close this?

**Comment by paul-marechal** [comment]
Yes surely !
