### ISSUE TITLE
LanguageId not passed

### ISSUE THREAD

**Issue by svenefftinge** [NeekSandhu/monaco-textmate#3]
Here 
https://github.com/NeekSandhu/monaco-textmate/blob/066ca3932a169131ec83ab861518738b755be0db/src/main.ts#L116

the grammar is loaded with only the scopename. So later the grammar always has languageid 0.

**Comment by zikaari** [comment]
Someone not familiar with the history of this repository will find this hilarious, but the truth is I really don't know why things are the way they are.

As you know this repo is modified version of vscode-textmate. I never investigated the internals (like why not languageID 0), just monkey patched at bare minimum level and shipped it out. *But* it "works".

I think I should've changed the API the way it fit the use case, by keeping it minimal and less moving parts. But I guess too late for that (or is it?).

My recommendation is that you avoid relying on low-level language ID management and try little bit abstraction as provided by `monaco-editor-textmate` (or see how it connects languageIDs and scope names for inspiration) 

Anyway, for the sake of curiosity, why can you not just rely on simple `loadGrammar`  and build on top of that instead?

**Comment by svenefftinge** [comment]
I figured that `vscode-textmate` now allows to configure the Onigurama lib, so I switched to it.
Maybe you should put that info on the Readme and deprecate this repo?

**Comment by zikaari** [comment]
I looked through the repo but couldn't find it. How is oniglib changed?

**Comment by svenefftinge** [comment]
You pass it through the RegistryOptions: https://github.com/Microsoft/vscode-textmate/blob/master/src/main.ts#L45

**Comment by zikaari** [comment]
Great thanks!

Will deprecate this one, although this one has few added features like very descriptive error that shows full import tree when an embedded tmlanguage can't be found that is needed by another tmlanguage.

I will try to PR that feature in vscode-textmate.

**Comment by zikaari** [comment]
MSFT team is pretty slow at responding to [requests](https://github.com/Microsoft/vscode-textmate/issues/79). Therefore this repo will live on until then :)
